sudo: false
language: ruby

env:
  matrix:
    - RAILS_VERSION=4.2.0
    - RAILS_VERSION=5.0.0
    - RAILS_VERSION=5.1.0
    - RAILS_VERSION=5.2.0.rc1

rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby
  - ruby-head

before_install: gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: RAILS_VERSION=5.2.0.rc1
